GLOBAL_LIST_INIT(ru_dictionary, list(
	"struck"					= "атакует",
	"pistol whipped"			= "пистолетирует",
	"hit"						= "бьёт",
	"attacked"					= "атакует",
	"pricked"					= "протыкает",
	"struck"					= "вмазывает",
	"absorbed"					= "пожирает",
	"gored"						= "унижает",
	"robusted"					= "робастит",
	"slashed"					= "кромсает",
	"stabbed"					= "втыкает",
	"sliced"					= "рубит",
	"diced"						= "нарезает",
	"cut"						= "нарезает",
	"stabbed"					= "протыкает",
	"stubbed"					= "вырезает",
	"poked"						= "дырявит",
	"torn"						= "тычет",
	"ripped"					= "рвёт",
	"cleaved"					= "мясует",
	"shanked"					= "тычет",
	"shivved"					= "насаживает",
	"battered"					= "колошматит",
	"bludgeoned"				= "месит",
	"thrashed"					= "лупит",
	"whacked"					= "раскатывает",
	"banned"					= "пермабанит",
	"brutalized"				= "насилует",
	"eviscerated"				= "опустошает",
	"disemboweled"				= "потрошит",
	"hacked"					= "кромсает",
	"carved"					= "вырезает",
	"bopped"					= "шлёпает",
	"slapped"					= "шлёпает",
	"bonked"					= "трахает",
	"impaled"					= "пронзает",
	"called"					= "вызванивает",
	"rang"						= "названивает",
	"disciplined"				= "учит",
	"chopped"					= "рубит",
	"beat"						= "бьёт",
	"smacked"					= "вмазывает",
	"sawed"						= "пилит",
	"clubbed"					= "долбит",
	"busted"					= "долбит",
	"swatted"					= "шлёпает",
	"pounded"					= "лупит",
	"pinched"					= "щиплет",
	"slammed"					= "ломает",
	"bashed"					= "колотит"
	))
/proc/ru_attack_verb(var/attack_verb, var/item)
	. = attack_verb
	if(!attack_verb)
		return
	if(GLOB.ru_dictionary[attack_verb])
		return GLOB.ru_dictionary[attack_verb]
	log_admin("Нет локализации для слова или фразы '[attack_verb]' для '[item]'")
